# Get/set build type variables
set(HOOT_BUILD_TYPE_DEBUG   "debug" CACHE INTERNAL "")
set(HOOT_BUILD_TYPE_RELEASE "release" CACHE INTERNAL "")

string(TOLOWER ${CMAKE_BUILD_TYPE} HOOT_BUILD_TYPE)
if(NOT HOOT_BUILD_TYPE)
set(HOOT_BUILD_TYPE ${HOOT_BUILD_TYPE_DEBUG} CACHE INTERNAL "")
endif(NOT HOOT_BUILD_TYPE)
